POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content":"po",
  "important":true
}

###

GET http://localhost:3001/api/notes

###

DELETE http://localhost:3001/api/notes/60cca0a41583f2197b32d05a

###
DELETE  http://localhost:3001/api/notes/60cc7111337dd422f12a055b
